config/routes.rb
Rails.application.routes.draw do

get 'manager' => 'managers#index'

root 'projects#index'

get 'login' => 'sessions#new'
post 'login' => 'sessions#create'
delete 'logout' => 'sessions#destroy'

resources :projects

resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
      user ||= User.new # guest user (not logged in)
      if user.role == "admin"
        can :manage, :all
        can :manage, :managers
      else
        can :read, Project

      end

  end

    # Define abilities for the passed in user here. For example:
    
    
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    
    #   can :update, Article, :published => true
    
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
end

app/models/project.rb
class Project < ActiveRecord::Base
	validates :title, presence: true
	validates :link, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password

	validates :name, presence: true
	validates :email, presence: true, uniqueness: true, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: :create }
	validates :password, :confirmation => true

	def admin?
		admin
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to login_url, :alert => exception.message
  end

  include SessionsHelper
  
end

app/controllers/managers_controller.rb
class ManagersController < ApplicationController

	include SessionsHelper
	
	authorize_resource :class => false

  def index
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	
	load_and_authorize_resource

	def index
		@projects = Project.all
	end


	def new
	end

	def create
		@project = Project.new(project_params)
		if @project.save
			redirect_to projects_path
		else
			render 'new'
		end
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])	

		if @project.update_attributes(project_params)
			redirect_to @project
		else	
			render 'edit'
		end
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy

		redirect_to root_path
	end


	private

		def project_params
			params.require(:project).permit(:title, :link, :description)
		end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	include SessionsHelper
  
  def new
  end
  
  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		log_in user
  		redirect_to manager_path
  	else
  		render 'new'
  		flash[:alert] = 'Ivalid email or password'
  	end
  end
  
	def destroy
		session.delete(:user_id)
    	redirect_to root_url
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	load_and_authorize_resource

	def index
			@users = User.all
	end	

	def new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to users_path
		else
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
		if @user.update_attributes user_params
			redirect_to users_path
		else
			render 'edit'
		end
	end

	def destroy
		User.find(params[:id]).destroy
		flash[:success] = "User deleted"
		redirect_to users_path
	end

	private

		def user_params
			params.require(:user).permit(:name, :email, :password, :password_confirmation, :admin)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/managers_helper.rb
module ManagersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper

	def list_of_projects
		@projects = Project.all
	end

end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		@current_user ||= User.find_by(id: session[:user_id])
		@current_user
	end

	# def self.log_out
	# 	session.delete(:user_id)
	# 	@current_user = nil
	# end

	def display_login_link
		if current_user.nil?
			link_to "Login", login_path
		else
			link_to "Logout", logout_path, method: :delete
		end
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>VRBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= csrf_meta_tags %>
</head>
<body>
	<header>
		<h1>Remi VR</h1>
	</header>
		<nav>
			<ul>
					<li><%= link_to "Home", projects_path%></li>
					<li><%= link_to "Manager", manager_path%></li>
					<li><a href="#">About me</a></li>
					<li><% if current_user%>
						<%= current_user.name %>
					<% end %>
					 <%= display_login_link %>
					</li>
				</ul>	
		</nav>
	</div>
	<div class="container-fluid">
		<div class="row">

			<div class="col-md-12">
				
				<h1 class="unauthorized"> <%= flash[:alert] %> </h1>


				<%= yield %>

				<p> <%= link_to "HOME", root_url%> </p>

				<%= link_to "Users", users_path %>

			</div>
		</div>
	</div>
</body>
</html>

app/views/managers/index.html.erb
<h1>Manage</h1>

<div class="dropdown">
	<button class="dropbtn" disabled>Projects</button>
	<div class="dropdown-content">
		<% list_of_projects.each do |project| %>
			<%= link_to project.title, project_path(project) %>
		<% end %>
	</div>
</div>

<% unless current_user.nil?%>
	<button class="dropbtn">
		<%= link_to current_user.name, user_path(current_user), class: "user-link"%>
	</button>
<% end %>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
	
	<ul> 
		<% @project.errors.full_messages.each do |message|%> 
			<li> <%= message %> </li>
		<% end %>
	</ul>
	
	<p>
		<%= f.label :title %>
		<%= f.text_field :title %>
	</p>	
	
	<p>
		<%= f.label :link %>
		<%= f.text_field :link %>
	</p>

	<p>
		<%= f.label :description %>
		<%= f.text_area :description%>
	</p>

	<p>
		<%= f.submit "Submit"%>
	</p>

<% end %>

app/views/projects/edit.html.erb
<h1> Update Project</h1>

<%= render 'form'%>

app/views/projects/index.html.erb
<h1>This is home page.</h1>

<% @projects.each do |project|%>
	<div class="project_wrapper">
		<h2 class="title"> <%= project.title %> </h2>
		<p class="description"> <%= project.description %> </p>
		<p class="date"> <%= project.created_at.strftime("%B, %d, %Y") %> </p>
		<p>	<%= link_to "Read more...", project%></p>
	</div>
<% end %>

<% if can? :create, @project %>
	<%= link_to "New Project", new_project_path %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

app/views/projects/show.html.erb
<div class="project_content">
	<h1> <%= @project.title %> </h1>

	<p> <%= @project.description%> </p>
	
	<p> <%= link_to(@project.link, "http://do-sport.herokuapp.com/")%> </p>
	
 <p class="date"> <%= @project.created_at.strftime("%B, %d, %Y")%>
	| <%= link_to "Edit", edit_project_path(@project)%>
	| <%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: "Are you sure?"} %>
 </p>
</div>

app/views/users/_user_form.html.erb
<%= form_for @user do |f| %>

	<ul> 
		<% @user.errors.full_messages.each do |message|%> 
			<li> <%= message %> </li>
		<% end %>
	</ul>

	<p>
		<%= f.label :name %>
		<%= f.text_field :name %>
	</p>
	<p>
		<%= f.label :email %>
		<%= f.email_field :email %>
	</p>
	<p>
		<%= f.label :password %>
		<%= f.password_field :password %>
	</p>
	<p>
		<%= f.label :password_confirmation %>
		<%= f.password_field :password_confirmation %>
	</p>

  <%= f.submit "Submit" %>
  

<% end %>

app/views/users/edit.html.erb
<%= render 'user_form' %>

app/views/users/index.html.erb
<%= link_to "New User", new_user_path %>

<% @users.each do |user| %>
	<h2> <%= link_to user.name, user_path(user) %></h2>
<% end %>

app/views/users/new.html.erb
<h1> |New User| </h1>
<%= render 'user_form' %>

app/views/users/show.html.erb
<h1><%= @user.name%></h1>
<h1><%= @user.email%></h1>
<h2><%= @user.id%></h2>
	<% if can? :update, @user %>
		<%= link_to "edit", edit_user_path %>
	<% end %>
	<% if can? :delete, @user%>
		<%= link_to "Delete", user_path, data: {confirm: "are you sure?"}, method: :delete %>
	<% end %>